name: Test

on:
  push:
    branches: [ master ]
    paths:
      - 'src/a/**'
      - '.eslintrc.js'
      - '**/package.json'
      - '**/yarn.lock'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/a/**'
      - '.eslintrc.js'
      - '**/package.json'
      - '**/yarn.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn test