name: Test

on:
  push:
    branches: [ master ]
    paths:
      - 'src/a/**/*.{js,jsx,ts,tsx}'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/a/**/*.{js,jsx,ts,tsx}'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn test